repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.7
- repo: local
  hooks:
  - id: python-safety-dependencies-check-main
    entry: safety
    args: [check, --file]
    language: python
    name: safety-api
    files: api/requirements.txt
- repo: local
  hooks:
  - id: python-safety-dependencies-check-cf
    entry: safety
    args: [check, --file]
    language: python
    name: safety-cf
    files: cloudfunctions/requirements.txt
- repo: local
  hooks:
  - id: python-safety-dependencies-check-dataflow
    entry: safety
    args: [check, --file]
    language: python
    name: safety-dataflow
    files: dataflow/requirements.txt
- repo: git://github.com/Lucas-C/pre-commit-hooks-bandit
  sha: v1.0.4
  hooks:
  - id: python-bandit-vulnerability-check
    name: bandit
    description: Python code vulnerabilities checker
    language: python
    types: [python]
    entry: bandit
    args: [-lll, --recursive, --exclude=.venv .]
    files: ''
- repo: local
  hooks:
  - id: flake8
    entry: flake8
    language: system
    name: flake8
    types: [python]